apiVersion: v1
kind: ConfigMap
metadata:
  name: faucet-config
  namespace: faucet
data:
  faucet.yaml: |
    vlans:
        vlan100:
            vid: 100
            faucet_vips: ["10.0.0.254/24"]
            faucet_mac: "00:00:00:00:00:11"
        vlan200:
            vid: 200
            faucet_vips: ["10.0.1.254/24"]
            faucet_mac: "00:00:00:00:00:22"
        vlan300:
            vid: 300
            faucet_vips: ["192.168.10.126/26"]
            faucet_mac: "00:00:00:00:00:33"
    dps:
        sw1:
            dp_id: 0x1
            hardware: "Open vSwitch"
            interfaces:
                1:
                    name: "host1"
                    description: "host1 network namespace"
                    native_vlan: vlan100
                2:
                    name: "host2"
                    description: "host2 network namespace"
                    native_vlan: vlan200
                3:
                    name: "frr"
                    description: "bgp network namespace"
                    native_vlan: vlan300
    routers:
        router-1:
          vlans: [vlan100, vlan200, vlan300]
        frr:
            bgp:
                vlan: vlan300
                as: 65000
                port: 9179
                routerid: '192.168.100.4'
                server_addresses: ['0.0.0.0'] # Ezt cser√©li le a Pod IP-re
                neighbor_addresses: ['192.168.1.29']
                neighbor_as: 65001