apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: faucet
  name: faucet
  namespace: faucet
spec:
  selector:
    matchLabels:
      app: faucet
  template:
    metadata:
      labels:
        app: faucet
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: "k3s-2"
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: "node.cilium.io/agent-not-ready"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
      hostNetwork: true 
      containers:
      - args:
        - |
          # Ez a parancs marad, de a fájl már a ConfigMap-ből van beolvasva
          echo "Generating faucet.yaml with Pod IP: $POD_IP"
          # A /etc/faucet-template/faucet.yaml most már a ConfigMap-ből jön.
          # Mivel a ConfigMap-ből csatolva a fájl neve megegyezik a kulccsal (faucet.yaml),
          # nem kell módosítani a fájl útvonalát.
          sed "s/0.0.0.0/$POD_IP/g" /etc/faucet-template/faucet.yaml > /etc/faucet/faucet.yaml
          echo "Config generated, starting Faucet..."
          exec /usr/local/bin/faucet
        command:
        - /bin/sh
        - -c
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: docker.io/faucet/faucet:latest
        imagePullPolicy: Always
        name: faucet
        ports:
        - containerPort: 6653
          protocol: TCP
        - containerPort: 9179
          protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/faucet-template
          name: faucet-config-template
          readOnly: true
        - mountPath: /etc/faucet
          name: faucet-config-runtime
      - image: docker.io/faucet/gauge:latest
        imagePullPolicy: Always
        name: gauge
        ports:
        - containerPort: 6654
          protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      volumes:
      - name: faucet-config-template
        configMap:
          name: faucet-config
          items:
          - key: faucet.yaml
            path: faucet.yaml
      - emptyDir: {}
        name: faucet-config-runtime
  updateStrategy:
    type: RollingUpdate